FROM openjdk:8-jdk-alpine
VOLUME /tmp
ADD target/microservice-employee-1.0.0.jar microservice-employee-1.0.0.jar
ENV JAVA_OPTS="-DPORT=10000"
ENTRYPOINT [ "sh","-c","java $JAVA_OPTS -jar microservice-employee-1.0.0.jar" ]
